from lib.Einkommenssteuer_Rechner_GNGE import *

testKfA = EkStCalculator(steuerfreibetrag=0, verbose=False, methoden_suffix='_kfa_only', ipge=True,
                         partielles_grundeinkommen=0.33*9408)
testKfA.add_method(
    stufe1_bg=0,
    stufe2_bg=testKfA.stufe1_bg-9408,
    stufe3_bg=testKfA.stufe2_bg-9408,
    stufe4_bg=testKfA.stufe3_bg-9408,
    stufe5_bg=testKfA.stufe4_bg-9408,
    stufe6_bg=testKfA.stufe5_bg-9408,
    stufe7_bg=testKfA.stufe5_bg,
    stufe8_bg=testKfA.stufe5_bg,
    stufe1_s=testKfA.stufe1_s,
    stufe2_s=testKfA.stufe1_s,
    stufe3_s=testKfA.stufe2_s,
    stufe4_s=testKfA.stufe3_s,
    stufe5_s=testKfA.stufe4_s,
    stufe6_s=testKfA.stufe5_s,
    stufe7_s=testKfA.stufe6_s,
    steuerfreibetrag=0,
    stufe1_proportional=False,
    stufe2_proportional=False,
    stufe3_proportional=False,
    stufe4_proportional=False,
    stufe5_proportional=True,
    stufe6_proportional=True,
    stufe7_proportional=True,
    stufe8_proportional=True,
    current_method_name='"Kindergeld für Alle" Ansatz')
testKfA.add_method(
    stufe1_bg=0,
    stufe2_bg=testKfA.stufe1_bg,
    stufe3_bg=testKfA.stufe2_bg,
    stufe4_bg=30000,
    stufe5_bg=testKfA.stufe3_bg,
    stufe6_bg=70000,
    stufe7_bg=testKfA.stufe4_bg,
    stufe8_bg=1e6 + 4,
    stufe1_s=0.3,
    stufe2_s=testKfA.stufe1_s + 0.215,
    stufe3_s=testKfA.stufe2_s + 0.215,
    stufe4_s=testKfA.stufe3_s + 0.13,
    stufe5_s=testKfA.stufe3_s + 0.13,
    stufe6_s=testKfA.stufe4_s + 0.10,
    stufe7_s=testKfA.stufe4_s + 0.10,
    stufe8_s=testKfA.stufe4_s + 0.10,
    steuerfreibetrag=0,
    stufe1_proportional=True,
    stufe2_proportional=False,
    stufe3_proportional=False,
    stufe4_proportional=False,
    stufe5_proportional=False,
    stufe6_proportional=True,
    stufe7_proportional=True,
    stufe8_proportional=True,
    current_method_name='Vorschlag Bruene Schloen',
    color='green')
testKfA.plot_einkommenssteuersatz(limit=250000, plot_ipge=False)

einkommenssteuer_baukje = EkStCalculator(steuerfreibetrag=9408, methoden_suffix='_baukjes_ueberlegungen',
                                        einkommen_ende=250000)
baukje_vorschlag_alt = False
if baukje_vorschlag_alt:
    einkommenssteuer_baukje.add_method(
        stufe1_bg=0,
        stufe2_bg=10000,
        stufe3_bg=12000,
        stufe4_bg=17000,
        stufe5_bg=40000,
        stufe1_s=0.30,
        stufe2_s=0.355,
        stufe3_s=0.45,
        stufe4_s=0.55,
        stufe5_s=0.55,
        steuerfreibetrag=0,
        stufe1_proportional=True,
        stufe2_proportional=False,
        stufe3_proportional=False,
        stufe4_proportional=True,
        stufe5_proportional=True,
        current_method_name='neuer Vorschlag Baukje')
einkommenssteuer_baukje.add_method(
    stufe1_bg=0,
    stufe2_bg=einkommenssteuer_baukje.stufe1_bg,
    stufe3_bg=einkommenssteuer_baukje.stufe2_bg,
    stufe4_bg=30000,
    stufe5_bg=einkommenssteuer_baukje.stufe3_bg,
    stufe6_bg=70000,
    stufe7_bg=einkommenssteuer_baukje.stufe4_bg,
    stufe8_bg=1e6 + 4,
    stufe1_s=0.3,
    stufe2_s=einkommenssteuer_baukje.stufe1_s + 0.215,
    stufe3_s=einkommenssteuer_baukje.stufe2_s + 0.215,
    stufe4_s=einkommenssteuer_baukje.stufe3_s + 0.13,
    stufe5_s=einkommenssteuer_baukje.stufe3_s + 0.13,
    stufe6_s=einkommenssteuer_baukje.stufe4_s + 0.10,
    stufe7_s=einkommenssteuer_baukje.stufe4_s + 0.10,
    stufe8_s=einkommenssteuer_baukje.stufe4_s + 0.10,
    steuerfreibetrag=0,
    stufe1_proportional=True,
    stufe2_proportional=False,
    stufe3_proportional=False,
    stufe4_proportional=False,
    stufe5_proportional=False,
    stufe6_proportional=True,
    stufe7_proportional=True,
    stufe8_proportional=True,
    current_method_name='Vorschlag Bruene Schloen')
einkommenssteuer_baukje.plot_einkommenssteuersatz(limit=100000, plot_ipge=False,
                                                  title='neuer Einkommenssteuervorschlag')